### ISSUE TITLE
Adding django installation to Dockerfile

### ISSUE THREAD

**Issue by justunsix** [mattwojo/helloworld-django#1]
https://github.com/mattwojo/helloworld-django/blob/78201a152007b3a0e06c7105eba8e7880ab41005/.devcontainer/Dockerfile#L7

Suggest adding
`RUN pip install django`

When running the project in VS Code, users can encounter error:
```sh
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment? 
```
since Django is not in the container. The change will ensure Django is installed.

**Comment by craigloewen-msft** [comment]
Fixed!

https://github.com/mattwojo/helloworld-django/commit/0e5c05d2b05f017822d2d7122982d9dbdc835b7f
